### ISSUE TITLE
Getting 429 response saying Too many request from OpenAi

### ISSUE THREAD

**Issue by nighotatul** [ut786/DataGPT#9]
Hi,

I am just download the code an start debugging with my own credential but getting 429 response saying too many request please help me out.
![Too many request](https://github.com/ut786/DataGPT/assets/37444019/16d7e220-78be-48a9-bc52-f3053f3cd55f)

**Comment by theumairtahir** [comment]
Hi, 
I think there's some issue with your OpenAI key please check you have added a valid key and your openai account has enough credit.

**Comment by theumairtahir** [comment]
The issue was from OpenAI response.
